name: Build Smart Brick APK
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Generate Gradle Wrapper
      run: |
        # Download and setup Gradle
        wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip
        unzip -q gradle-8.7-bin.zip
 
        # Generate wrapper files
        gradle-8.7/bin/gradle wrapper --gradle-version 8.7
 
        # Make gradlew executable
        chmod +x gradlew
 
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
 
    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace
 
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: SmartBrickNFC-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
